#!/bin/bash
####Installation of packages in shell script####
R="\e[31m" #Red
G="\e[32m" #Green
Y="\e[33m" #Yellow
N="\e[0m"  #No Color

LOG_FOLDER="/var/log/shellscript"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOG_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOG_FOLDER
echo "script started at $(date)" | tee -a $LOG_FILE

SOURCE_DIR=/home/ec2-user/app-logs

if [ ! -d $SOURCE_DIR]; then
    echo -e "ERROR: $SOURCE_DIR directory does not exist $N" | tee -a $LOG_FILE
    exit 1
fi

FILES_TO_DELETE=$(find $SOURCE_DIR -type f -mtime +14)